move from popover to tooltip
RedHatInsights/notifications-frontend pull request #302
Opened 2022-06-10 15:38 UTC by aferd

https://user-images.githubusercontent.com/86322239/173100796-3594268d-9119-419f-a988-990dba8aeef2.mov

2022-06-10 19:53 UTC, josejulio requested changes
Other application and IIRC the designs uses the `Popover`-style (click to show).

Could you try the following?
- Control the state with the `isVisible` prop on the popover? 
-  Use the `shouldClose` / `shouldOpen` functions - they receive an event. Calling `event.stopPropagation();` should stop the event from reaching the expanded button.

Something else that could work is to rearrange the components. 

Right now we have
```tsx
<ExpandingToggle>
  <Split>
    <SplitItem>Tittle</SplitItem>
    <SplitItem>PossibleButton</SplitItem>
    <SplitItem>Popover</SplitItem>
  </Split>
</ExpandingToggle>
```

Maybe it could look good and work well with:
```tsx
  <Split>
    <ExpandingToggle><SplitItem>Tittle</SplitItem></ExpandingToggle>
    <SplitItem>PossibleButton</SplitItem>
    <SplitItem>Popover</SplitItem>
  </Split>
```

2022-06-13 19:32 UTC, aferd commented
https://user-images.githubusercontent.com/86322239/173430442-d9691cae-5001-4f32-8938-da9607696843.mov

2022-06-13 19:52 UTC, josejulio commented
It looks to me like there is an extra space between "Behavior groups" and the `(6)` that wasn't there. Could you check?

2022-06-13 20:01 UTC, mmenestr commented
Yes, I agree there's too much space between the two - should be 16px only

2022-06-13 21:06 UTC, aferd commented
<img width="501" alt="Screen Shot 2022-06-13 at 5 06 07 PM" src="https://user-images.githubusercontent.com/86322239/173445447-41e56cf8-6e20-4250-b7dc-c34ffc03ab62.png">

2022-06-13 22:28 UTC, josejulio approved these changes
lgtm

2022-06-14 12:51 UTC, mmenestr commented
Just one small thing - all actionable icons should be grey by default, and black only on hover and on click! So in the screenshot, the question circle should be - pf-global--color--200


![image](https://user-images.githubusercontent.com/51165119/173581259-c3488ca7-a8a3-4d9c-9fb8-52e19db31634.png)

2022-06-14 19:06 UTC, aferd commented
https://user-images.githubusercontent.com/86322239/173669147-dabc96bd-b98f-4a36-8c8b-52d2b83877e0.mov

2022-06-14 19:07 UTC, aferd commented
@mmenestr changed to default!

2022-06-14 19:35 UTC, josejulio commented on src/pages/Notifications/List/BehaviorGroupsSection.tsx
> +    color: global_Color_200.var,
Is this needed? I though it would work out of the box without this color.

2022-06-14 19:36 UTC, josejulio approved these changes
lgtm

2022-06-14 19:45 UTC, aferd commented on src/pages/Notifications/List/BehaviorGroupsSection.tsx
> +    color: global_Color_200.var,
ah, nope. not needed, thanks! I did not try without it. It's been removed.

2022-06-14 20:47 UTC, mmenestr commented
Looks good thank you!

2022-06-15 13:09 UTC, merged