RHCLOUD-23554 Add text in UI to inform user that an email notif is being forced
RedHatInsights/notifications-frontend pull request #392
Opened 2023-04-06 17:26 UTC by aferd

<img width="540" alt="Screen Shot 2023-04-06 at 1 23 35 PM" src="https://user-images.githubusercontent.com/86322239/230452093-2fc89d7d-a350-4ac3-b01b-3d03433e5d13.png">
this is what it would look like when there is a forced email. there is currently NO apps sending forced emails so you will not see this in the UI as of now.

2023-04-06 19:57 UTC, josejulio requested changes

2023-04-06 19:57 UTC, josejulio commented on src/components/Notifications/Recipient.tsx
> +    const [ ignorePref ] = React.useState<EmailSystemProperties>();
I think you still need to load this value into the `Action`.

Here is how to do it:

1. Update [NotificationAdapter](https://github.com/josejulio/notifications-frontend/blob/f711c5d03c6f66372489b3b44c9355cbc1b2fc5b/src/types/adapters/NotificationAdapter.ts#L35) to use the ignore preferences variable (`integration.ignorePreferences`) and pass it to `NotificationUserRecipient`
2. Update [NotificationUserRecipient](https://github.com/josejulio/notifications-frontend/blob/ffc76263cfc72f160bc31f693c3ffbeaa5d395b2/src/types/Recipient.ts#L56) to receive a third boolean for ignorePreferences, and assign it accordingly. You will need to update other places where it's called.
3.  The setting is per recipient. i.e. the recipient "all users" might not be forced but "send to admins" might be forced so I suggest to update:
`Users: {join(users.map(u => u.displayName), CommaSeparator)}` to something like:
```
Users: {join(users.map(u => <>
  {u.displayName}
  {u.ignoreUserPreferences && <span className={ greyColorName }> { props.action.integration.name }
                        <Tooltip content="This integration has been disabled. This action wil not fire until it is enabled." position="bottom">
                            <BanIcon className={ disabledLabelClassName } />
                        </Tooltip>
                    </span>)
</>), CommaSeparator)}
```
The lock icon should show only for the users that are forced.

Alternatively you could display it on the end by checking if there is at least one forced recipient:
```
const ignoreUserPreferences = users.some(u => u.ignoreUserPreferences)
```

4. Theorically the groups could also be forced, but there is no way to set it right now.

2023-04-12 22:45 UTC, aferd commented
@josejulio when you get time can you re-review? thanks!

2023-04-17 14:35 UTC, josejulio commented on src/types/Recipient.ts
>      public equals(recipient: Recipient) {
Could you update this equal to include the `ignorePreferences`? 

Change `return recipient.sendToAdmin === this.sendToAdmin;` to `return recipient.sendToAdmin === this.sendToAdmin && recipient.ignorePreferences === this.ignorePreferences;`

2023-04-17 14:47 UTC, josejulio approved these changes
lgtm

2023-04-17 14:52 UTC, merged